name: Build
on:
  push:
    tags:
    - '*'

jobs:
  build-tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build
        run: ./build.sh
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/$GITHUB_ACTOR/blog:${GITHUB_REF##*/} .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/blog:${{ github.ref }}
